"""Add photos, warehouse and stock tables

Revision ID: 3d972d16879b
Revises: 4bc71726dfe7
Create Date: 2023-05-11 10:34:50.263162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d972d16879b'
down_revision = '4bc71726dfe7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
