"""Add CASCADE for ForeignKeys

Revision ID: 9b99b6134b9d
Revises: 3d972d16879b
Create Date: 2023-05-26 00:22:56.292388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b99b6134b9d'
down_revision = '3d972d16879b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_photo_product_id_fkey', 'product_photo', type_='foreignkey')
    op.create_foreign_key(None, 'product_photo', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('stock_product_id_fkey', 'stock', type_='foreignkey')
    op.drop_constraint('stock_warehouse_id_fkey', 'stock', type_='foreignkey')
    op.create_foreign_key(None, 'stock', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'stock', 'warehouse', ['warehouse_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock', type_='foreignkey')
    op.drop_constraint(None, 'stock', type_='foreignkey')
    op.create_foreign_key('stock_warehouse_id_fkey', 'stock', 'warehouse', ['warehouse_id'], ['id'])
    op.create_foreign_key('stock_product_id_fkey', 'stock', 'product', ['product_id'], ['id'])
    op.drop_constraint(None, 'product_photo', type_='foreignkey')
    op.create_foreign_key('product_photo_product_id_fkey', 'product_photo', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
